# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "project"
    label: "Project"
    folder: "_projects/"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Period", name: "period", widget: "number", default: 2023 }
      - { label: "Site", name: "site", widget: "string" }
      - { label: "Github", name: "github", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Categorie", name: "categorie", widget: "string" }
