# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "project"
    label: "Project"
    folder: "_projects/"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Preview Image", name: "preview", widget: "image" }
      - {
          label: "Images Desktop",
          name: "images-desktop",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - {
          label: "Images Mobile",
          name: "images-mobile",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - { label: "Period", name: "period", widget: "number", default: 2023 }
      - { label: "Site", name: "site", widget: "string", required: false }
      - { label: "Github", name: "github", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Categorie", name: "categorie", widget: "string" }
